### ISSUE TITLE
Errors in derived fields examples

### ISSUE THREAD

**Issue by kyleaoman** [cbyrohl/scida#116]
```
Python 3.11.6 (main, Oct  3 2023, 00:00:00) [GCC 13.2.1 20230728 (Red Hat 13.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> 
>>> from scida import load
Warning! Using default configuration. Please adjust/replace in '/home/txwx36/.config/scida/config.yaml'.
>>> from scida.fields import FieldContainer
>>> groupnames = ["PartType0", "Subhalo"]  
>>> fielddefs = FieldContainer(containers=groupnames)
>>> 
>>> @fielddefs.register_field("PartType0") 
... def Volume(arrs, **kwargs):
...     return arrs["Masses"]/arrs["Density"]
... 
>>> @fielddefs.register_field("all") 
... def GroupDistance3D(arrs, snap=None):
...     """Returns distance to hosting group center. Returns rubbish if not actually associated with a group."""
...     import dask.array as da
...     boxsize = snap.header["BoxSize"]
...     pos_part = arrs["Coordinates"]
...     groupid = arrs["GroupID"]
...     if hasattr(groupid, "magnitude"):
...         groupid = groupid.magnitude
...         boxsize *= snap.ureg("code_length")
...     pos_cat = snap.data["Group"]["GroupPos"][groupid]
...     dist3 = pos_part-pos_cat
...     dist3 = da.where(dist3>boxsize/2.0, boxsize-dist3, dist3)
...     dist3 = da.where(dist3<=-boxsize/2.0, boxsize+dist3, dist3) # PBC
...     return dist3
... 
>>> @fielddefs.register_field("all")
... def GroupDistance(arrs, snap=None):
...     import dask.array as da
...     dist3 = arrs["GroupDistance3D"]
...     dist = da.sqrt((dist3**2).sum(axis=1))
...     dist = da.where(arrs["GroupID"]==-1, np.nan, dist) # set unbound gas to nan
...     return dist
... 
>>> ds = load("snapdir_030")
>>> ds.data.merge(fielddefs)
>>> gas = ds.data["PartType0"]
>>> print(gas["Volume"])
dask.array<truediv, shape=(19124236,), dtype=float32, chunksize=(19124236,), chunktype=numpy.ndarray> code_length ** 3
>>> print(gas["GroupDistance"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/txwx36/code/scida/src/scida/fields.py", line 240, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "/home/txwx36/code/scida/src/scida/fields.py", line 327, in _getitem
    field = self._instantiate_field(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/txwx36/code/scida/src/scida/fields.py", line 361, in _instantiate_field
    field = func(self, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^
  File "<stdin>", line 4, in GroupDistance
  File "/home/txwx36/code/scida/src/scida/fields.py", line 240, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "/home/txwx36/code/scida/src/scida/fields.py", line 327, in _getitem
    field = self._instantiate_field(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/txwx36/code/scida/src/scida/fields.py", line 361, in _instantiate_field
    field = func(self, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^
  File "<stdin>", line 7, in GroupDistance3D
  File "/home/txwx36/code/scida/src/scida/fields.py", line 240, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "/home/txwx36/code/scida/src/scida/fields.py", line 332, in _getitem
    raise KeyError("Unknown field '%s'" % key)
KeyError: "Unknown field 'GroupID'"
>>> print(gas["Subhalo"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/txwx36/code/scida/src/scida/fields.py", line 240, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "/home/txwx36/code/scida/src/scida/fields.py", line 332, in _getitem
    raise KeyError("Unknown field '%s'" % key)
KeyError: "Unknown field 'Subhalo'"
```

The first error (`KeyError: "Unknown field 'GroupID'"`) might be a mismatch between the contents of the `snapshot_030` example provided and what's assumed in `TNG50-4_snapshot`? The second error looks like something like this might have been expected?

```
@fielddefs.register_field("all") 
def Subhalo(arrs, snap=None):
    ...
```

Or perhaps there's an assumed step of linking to a group catalogue that I'm missing (that should be signposted to?).

**Comment by cbyrohl** [comment]
That is right. The latter examples require a snapshot with a halo catalog. I will add another example taht does not require the halo catalog, and add an info box for the advanced examples, which need such.
